apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
 name: superuser-binding
roleRef:
 kind: ClusterRole
 name: superuser
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: c9c4de85-4216-4129-99b7-09c8e39c3ad5
  apiGroup: rbac.authorization.k8s.io