apiVersion: v1 
kind: Service 
metadata: 
  name: busapp-01
  namespace: dev-space
spec: 
  selector: 
    app: bus 
    tier: frontend 
  ports: 
    - port: 8081 
      targetPort: 8001 
  type: LoadBalancer